[
build
]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[
deploy
]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[
deploy.healthcheck
]
path = "/"
interval = "30s"
timeout = "10s"
retries = 3